spring.application.name=PTIT_CNTT2_IT211_Session12_ex2

logging.level.root=WARN
logging.level.ra.edu.ptit_cntt2_it211_session12_ex2.controller=INFO
logging.level.ra.edu.ptit_cntt2_it211_session12_ex2.service=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger - %msg%n
